AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  HTTPCLIENTLOGREQUEST:
    Description: 'Required. Http client log request'
    Type: 'String'

  HTTPCLIENTLOGRESPONSE:
    Description: 'Required. Http client log response'
    Type: 'String'

  DBPATH:
    Description: 'Required. Path to sqlite database'
    Type: 'String'

  FINANCECMBASEURI:
    Description: 'Required. Finance - CM URI base'
    Type: 'String'

  FINANCECMAUTHENTICATIONPATH:
    Description: 'Required. Finance - CM authentication path'
    Type: 'String'

  FINANCECMVALIDATIONPATH:
    Description: 'Required. Finance - CM validation path'
    Type: 'String'

  FINANCECMHOMEPATH:
    Description: 'Required. Finance - CM home path'
    Type: 'String'

  FINANCECMDOWNLOADPATH:
    Description: 'Required. Finance - CM download path'
    Type: 'String'

  FINANCECMTRANSACTIONPATH:
    Description: 'Required. Finance - CM transaction path'
    Type: 'String'

  FINANCECMUSERNAME:
    Description: 'Required. Finance - CM username'
    Type: 'String'

  FINANCECMPASSWORD:
    Description: 'Required. Finance - CM password'
    Type: 'String'

  FINANCECMOTPSESSION:
    Description: 'Required. Finance - Path to CM otp session'
    Type: 'String'

  FINANCECMAPKID:
    Description: 'Required. Finance - APK id'
    Type: 'String'

  FINANCETRANSACTIONSDIR:
    Description: 'Required. Finance - Path to transactions directory'
    Type: 'String'

  FINANCECMACCOUNTS:
    Description: 'Required. Finance - CM accounts configuration'
    Type: 'String'

  FINANCES3TRANSACTIONSREGION:
    Description: 'Required. Finance - AWS S3 bucket region'
    Type: 'String'

  FINANCES3TRANSACTIONSBUCKET:
    Description: 'Required. Finance - AWS S3 bucket name'
    Type: 'String'

  FINANCES3TRANSACTIONSPUBLICKEY:
    Description: 'Required. Finance - AWS S3 client id'
    Type: 'String'

  FINANCES3TRANSACTIONSSECRETKEY:
    Description: 'Required. Finance - AWS S3 client secret'
    Type: 'String'

  FINANCES3TRANSACTIONSPREFIX:
    Description: 'Required. Finance - AWS S3 bucket prefix'
    Type: 'String'

  FINANCESETUPVOLUMEMAXKEYS:
    Description: 'Required. Finance - Max number of downloads per page when setting up volume'
    Type: 'Number'

  FINANCEWAGESTATEMENTS:
    Description: 'Required. Finance - Wage statements configuration'
    Type: 'String'

  HEATERSBASEURI:
    Description: 'Required. Heaters - Base URI'
    Type: 'String'

  HEATERSUSERNAME:
    Description: 'Required. Heaters - Username'
    Type: 'String'

  HEATERSPASSWORD:
    Description: 'Required. Heaters - Password'
    Type: 'String'

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Runtime: java11
    Environment:
      Variables:
        HTTPCLIENT_LOGREQUEST: !Ref HTTPCLIENTLOGREQUEST
        HTTPCLIENT_LOGRESPONSE: !Ref HTTPCLIENTLOGRESPONSE
        DB_PATH: !Ref DBPATH
        FINANCE_CM_BASE_URI: !Ref FINANCECMBASEURI
        FINANCE_CM_AUTHENTICATION_PATH: !Ref FINANCECMAUTHENTICATIONPATH
        FINANCE_CM_VALIDATION_PATH: !Ref FINANCECMVALIDATIONPATH
        FINANCE_CM_HOME_PATH: !Ref FINANCECMHOMEPATH
        FINANCE_CM_DOWNLOAD_PATH: !Ref FINANCECMDOWNLOADPATH
        FINANCE_CM_TRANSACTION_PATH: !Ref FINANCECMTRANSACTIONPATH
        FINANCE_CM_USERNAME: !Ref FINANCECMUSERNAME
        FINANCE_CM_PASSWORD: !Ref FINANCECMPASSWORD
        FINANCE_CM_OTPSESSION: !Ref FINANCECMOTPSESSION
        FINANCE_CM_APKID: !Ref FINANCECMAPKID
        FINANCE_TRANSACTIONS_DIR: !Ref FINANCETRANSACTIONSDIR
        FINANCE_CM_ACCOUNTS: !Ref FINANCECMACCOUNTS
        FINANCE_S3_TRANSACTIONSREGION: !Ref FINANCES3TRANSACTIONSREGION
        FINANCE_S3_TRANSACTIONS_BUCKET: !Ref FINANCES3TRANSACTIONSBUCKET
        FINANCE_S3_TRANSACTIONS_PUBLICKEY: !Ref FINANCES3TRANSACTIONSPUBLICKEY
        FINANCE_S3_TRANSACTIONS_SECRETKEY: !Ref FINANCES3TRANSACTIONSSECRETKEY
        FINANCE_S3_TRANSACTIONS_PREFIX: !Ref FINANCES3TRANSACTIONSPREFIX
        FINANCE_SETUP_VOLUME_MAXKEYS: !Ref FINANCESETUPVOLUMEMAXKEYS
        FINANCE_WAGE_STATEMENTS: !Ref FINANCEWAGESTATEMENTS

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "eu-west-3a"

  EfsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: "mnt target sg"
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: "0.0.0.0/0"

  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose

  AccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref FileSystem
      PosixUser:
        Uid: "1001"
        Gid: "1001"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1001"
          OwnerUid: "1001"
          Permissions: "755"

  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref Subnet1
      SecurityGroups:
        - !Ref EfsSecurityGroup

  ApiGatewayApi:
    Type: AWS::Serverless::HttpApi

  HeatersApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../heaters-api/target/scala-2.13/heaters-api.jar
      Handler: sre.api.heaters.Handler::handleRequest
      Events:
        heatersProxyEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGatewayApi
            Path: /heaters/{proxy+}
            PayloadFormatVersion: "2.0"
            Method: ANY
      Environment:
        Variables:
          HTTPCLIENT_LOGREQUEST: !Ref HTTPCLIENTLOGREQUEST
          HTTPCLIENT_LOGRESPONSE: !Ref HTTPCLIENTLOGRESPONSE
          HEATERS_BASEURI: !Ref HEATERSBASEURI
          HEATERS_USERNAME: !Ref HEATERSUSERNAME
          HEATERS_PASSWORD: !Ref HEATERSPASSWORD

  FinanceReindexStep:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../finance-api/target/scala-2.13/finance-api.jar
      Handler: sre.api.finance.tasks.Reindex::handleRequest
      FileSystemConfigs:
      - Arn: !GetAtt AccessPoint.Arn
        LocalMountPath: "/mnt/efs"
      VpcConfig:
        SecurityGroupIds:
          - !Ref EfsSecurityGroup
        SubnetIds:
          - !Ref Subnet1
    DependsOn: "MountTarget1"

  FinanceSnapshotStep:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../finance-api/target/scala-2.13/finance-api.jar
      Handler: sre.api.finance.tasks.Snapshot::handleRequest

  FinanceCheckOtpStep:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../finance-api/target/scala-2.13/finance-api.jar
      Handler: sre.api.finance.tasks.CheckOtp::handleRequest

  FinanceImportStatementsStep:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../finance-api/target/scala-2.13/finance-api.jar
      Handler: sre.api.finance.tasks.ImportStatements::handleRequest

  FinanceSetupVolumeStep:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../finance-api/target/scala-2.13/finance-api.jar
      Handler: sre.api.finance.tasks.SetupVolume::handleRequest
      FileSystemConfigs:
      - Arn: !GetAtt AccessPoint.Arn
        LocalMountPath: "/mnt/efs"
      VpcConfig:
        SecurityGroupIds:
          - !Ref EfsSecurityGroup
        SubnetIds:
          - !Ref Subnet1
    DependsOn: "MountTarget1"

  FinanceResetVolumeStep:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../finance-api/target/scala-2.13/finance-api.jar
      Handler: sre.api.finance.tasks.ResetVolume::handleRequest
      FileSystemConfigs:
      - Arn: !GetAtt AccessPoint.Arn
        LocalMountPath: "/mnt/efs"
      VpcConfig:
        SecurityGroupIds:
          - !Ref EfsSecurityGroup
        SubnetIds:
          - !Ref Subnet1
    DependsOn: "MountTarget1"

  FinanceRefreshPeriodTask:
    Type: AWS::Serverless::StateMachine
    Properties:
      Policies: arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Definition:
        Comment: Refresh current period
        StartAt: ImportStatements
        States:
          ImportStatements:
            Type: Task
            Resource: !GetAtt FinanceImportStatementsStep.Arn
            TimeoutSeconds: 60
            Next: EitherEndOrSignin

          EitherEndOrSignin:
            Type: Choice
            Choices:
              - Variable: $.otpRequest
                IsNull: false
                Next: OtpCheckTask
            Default: End

          OtpCheckTask:
            Type: Task
            Resource: !GetAtt FinanceCheckOtpStep.Arn
            TimeoutSeconds: 30
            Next: EitherImportStatementsOrCheckOtp

          EitherImportStatementsOrCheckOtp:
            Type: Choice
            Choices:
              - Variable: $.status
                StringEquals: "validated"
                Next: End
              - Variable: $.validated
                StringEquals: "pending"
                Next: OtpWaitTask

          OtpWaitTask:
            Type: Wait
            Seconds: 2
            Next: OtpCheckTask

          End:
            Type: Pass
            End: true

  FinanceAnalyticsTask:
    Type: AWS::Serverless::StateMachine
    Properties:
      Policies: arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Definition:
        Comment: Snapshot accounts state and run analytics
        StartAt: SnapshotTask
        States:
          SnapshotTask:
            Type: Task
            Resource: !GetAtt FinanceSnapshotStep.Arn
            TimeoutSeconds: 60
            Next: EitherReindexOrSignin

          EitherReindexOrSignin:
            Type: Choice
            Choices:
              - Variable: $.files
                IsNull: false
                Next: ReindexTask
              - Variable: $.otpRequest
                IsNull: false
                Next: OtpCheckTask

          ReindexTask:
            Type: Task
            Resource: !GetAtt FinanceReindexStep.Arn
            TimeoutSeconds: 60
            End: true

          OtpCheckTask:
            Type: Task
            Resource: !GetAtt FinanceCheckOtpStep.Arn
            TimeoutSeconds: 30
            Next: EitherSnapshotOrCheckOtp

          EitherSnapshotOrCheckOtp:
            Type: Choice
            Choices:
              - Variable: $.status
                StringEquals: "validated"
                Next: SnapshotTask
              - Variable: $.validated
                StringEquals: "pending"
                Next: OtpWaitTask

          OtpWaitTask:
            Type: Wait
            Seconds: 2
            Next: OtpCheckTask

  FinanceSetupTask:
    Type: AWS::Serverless::StateMachine
    Properties:
      Policies: arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Definition:
        Comment: Setup properly EFS volume with transactions
        StartAt: ResetVolumeTask
        States:
          ResetVolumeTask:
            Type: Task
            Resource: !GetAtt FinanceResetVolumeStep.Arn
            TimeoutSeconds: 60
            Next: SetupVolumeTask

          SetupVolumeTask:
            Type: Task
            Resource: !GetAtt FinanceSetupVolumeStep.Arn
            TimeoutSeconds: 60
            Next: EitherContinueOrEnd

          EitherContinueOrEnd:
            Type: Choice
            Choices:
              - Variable: $.continuationToken
                IsNull: false
                Next: SetupVolumeTask
              - Variable: $.continuationToken
                IsNull: true
                Next: End

          End:
            Type: Pass
            End: true
