name: ci-compile
on:
  push:
  pull_request:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"

    - name: Compile
      run: sbt -Dfile.encoding=UTF-8 -v compile
