name: ci-master
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Decrypt test resources
      run: |
        echo ${{github.ref}}
        mkdir -p src/test/resources/
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output resources.tar resources.tar.gpg
        tar xvf resources.tar --directory src/test/resources/

    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"

    - name: Test
      run: |
        sbt -Dfile.encoding=UTF-8 -v test
